language: node_js
os:
  - linux
  - osx
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "stable"
script:
  - npm run codecov
deploy:
  provider: npm
  email: bernhard.bezdek@googlemail.com
  api_key: $NPM_TOKEN
  on:
    branch: master