language: node_js
os:
  - linux
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "stable"
git:
  depth: 5
cache: yarn
script:
  - npm run codecov
deploy:
  provider: npm
  email: bernhard.bezdek@googlemail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
