language: node_js
os:
  - linux
node_js:
  - "6"
  - "7"
  - "8"
  - "stable"
deploy:
  provider: npm
  email: bernhard.bezdek@googlemail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
script:
  on:
    branch: master
  - npm run codecov